"""project_stage_template 加 deleted_at（模块库删除改为软删除）

Revision ID: 15607e58a390
Revises: c29c7ea1e713
Create Date: 2026-09-13 20:32:42.725014

模块库条目被项目引用过，物理删除会丢掉关卡的来源信息，因此改为软删：
列表/详情自动过滤已删条目，已被项目引用的条目仍然不允许"删"（软删也不行）。
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '15607e58a390'
down_revision: str | None = 'c29c7ea1e713'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_stage_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_stage_template', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
