"""删掉 student_skill.state（技能不再分三态，只看进度）

Revision ID: 1e6666811ff5
Revises: 82a4f9ff26f4
Create Date: 2026-09-13 23:08:48.300452

技能展示口径改成"看进度（0~100）"，LOCKED/ACTIVATED/MASTERED 三态不再需要；
activated_at / mastered_at 保留，语义调整为"首次产生进度""首次达到 100%"的时间。
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1e6666811ff5'
down_revision: str | None = '82a4f9ff26f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_skill', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_skill', schema=None) as batch_op:
        # 回滚时表里可能已有数据，非空列必须带临时默认值才加得上
        batch_op.add_column(
            sa.Column('state', sa.VARCHAR(length=20), nullable=False, server_default='LOCKED')
        )

    # ### end Alembic commands ###
