"""新增 project_file：项目附件（报告模板 / 数据文件等）

Revision ID: 2fa52fe757e0
Revises: 1e6666811ff5
Create Date: 2026-09-14 00:09:11.054464

文件本体不入库：上传时写本地存储（bucket + object_key），元数据记在 file_asset，
这张表只保存"某个项目挂了哪些文件、用途是什么"，一个项目同一个文件只挂一次。
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2fa52fe757e0'
down_revision: str | None = '1e6666811ff5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_file',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_asset_id', sa.Integer(), nullable=False),
    sa.Column('file_kind', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('sort_no', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_asset_id'], ['file_asset.id'], name=op.f('fk_project_file_file_asset_id')),
    sa.ForeignKeyConstraint(['project_id'], ['training_project.id'], name=op.f('fk_project_file_project_id')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['sys_user.id'], name=op.f('fk_project_file_uploaded_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_file')),
    sa.UniqueConstraint('project_id', 'file_asset_id', name='uk_project_file')
    )
    with op.batch_alter_table('project_file', schema=None) as batch_op:
        batch_op.create_index('idx_project_file_project', ['project_id', 'file_kind'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_file', schema=None) as batch_op:
        batch_op.drop_index('idx_project_file_project')

    op.drop_table('project_file')
    # ### end Alembic commands ###
