"""add sys_user password_hash, drop sys_role password

Revision ID: 3f4a00612ab8
Revises: d5b772b56392
Create Date: 2026-09-11 14:46:09.957352
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

#: 存量账号回填用的默认密码哈希（明文 123456，见 settings.default_password）。
#: 这里写死字面量，避免迁移脚本依赖应用代码（app/services/password.py）将来被改动。
DEFAULT_PASSWORD_HASH = (
    "pbkdf2_sha256$260000$3ad9d4e936bff3344b943f08be0b3a79"
    "$2b525fd03075a4c29cc532193803ad2bb46ef25eeae9cf5cbf23533a64a37fe2"
)


# revision identifiers, used by Alembic.
revision: str = '3f4a00612ab8'
down_revision: str | None = 'd5b772b56392'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_role', schema=None) as batch_op:
        batch_op.drop_column('password')

    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True))

    # 存量账号（如种子里的 admin）回填默认密码，避免升级后无法登录
    op.execute(
        sa.text(
            "UPDATE sys_user SET password_hash = :pwd_hash WHERE password_hash IS NULL"
        ).bindparams(pwd_hash=DEFAULT_PASSWORD_HASH)
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('sys_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
