"""init schema

Revision ID: 43cc8d080ca4
Revises: 
Create Date: 2026-09-11 01:15:25.960958
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.core.types


# revision identifiers, used by Alembic.
revision: str = '43cc8d080ca4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_stage_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stage_key', sa.String(length=50), nullable=False, comment='七大模块 code'),
    sa.Column('stage_name', sa.String(length=100), nullable=False, comment='模块名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='说明/描述'),
    sa.Column('default_required', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='默认是否必填'),
    sa.Column('default_weight', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False, comment='默认分值占比'),
    sa.Column('default_requirement', sa.Text(), nullable=True, comment='默认作答要求'),
    sa.Column('default_accept_standard', sa.Text(), nullable=True, comment='默认验收标准'),
    sa.Column('sort_no', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='展示排序'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_stage_template')),
    sa.UniqueConstraint('stage_key', name='uk_stage_template_key')
    )
    op.create_table('skill_tree',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tree_code', sa.String(length=50), nullable=False, comment='技能树编码'),
    sa.Column('tree_name', sa.String(length=100), nullable=False, comment='技能树名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='说明/描述'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ENABLED'"), nullable=False, comment='ENABLED/DISABLED'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', app.core.types.TZDateTime(), nullable=True, comment='软删除时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_tree')),
    sa.UniqueConstraint('tree_code', name='uk_skill_tree_code')
    )
    op.create_table('sys_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('perm_code', sa.String(length=100), nullable=False, comment='权限编码'),
    sa.Column('perm_name', sa.String(length=100), nullable=False, comment='权限名称'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_permission')),
    sa.UniqueConstraint('perm_code', name='uk_sys_perm_code')
    )
    op.create_table('sys_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False, comment='角色编码'),
    sa.Column('role_name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('password', sa.String(length=100), nullable=True, comment='预留：mock 登录/联调；生产走 SSO'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_role')),
    sa.UniqueConstraint('role_code', name='uk_sys_role_code')
    )
    op.create_table('sys_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_no', sa.String(length=50), nullable=False, comment='学号/工号'),
    sa.Column('real_name', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('user_type', sa.String(length=20), nullable=False, comment='STUDENT/TEACHER/ADMIN'),
    sa.Column('ext_uid', sa.String(length=64), nullable=True, comment='学校 IDP 唯一标识'),
    sa.Column('major_name', sa.String(length=100), nullable=True, comment='专业'),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='头像地址'),
    sa.Column('phone', sa.String(length=32), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False, comment='ACTIVE/DISABLED'),
    sa.Column('last_login_at', app.core.types.TZDateTime(), nullable=True, comment='最近登录时间'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', app.core.types.TZDateTime(), nullable=True, comment='软删除时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_user')),
    sa.UniqueConstraint('user_no', name='uk_sys_user_no')
    )
    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.create_index('idx_sys_user_type_status', ['user_type', 'status'], unique=False)
        batch_op.create_index('uk_sys_user_ext', ['ext_uid'], unique=True, sqlite_where=sa.text('ext_uid IS NOT NULL'))

    op.create_table('ai_qa_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True, comment='会话标题'),
    sa.Column('subject', sa.String(length=100), nullable=True, comment='课程/知识范围'),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False, comment='ACTIVE/CLOSED'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['student_id'], ['sys_user.id'], name=op.f('fk_ai_qa_session_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_qa_session'))
    )
    op.create_table('class_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False, comment='班级名称'),
    sa.Column('grade_year', sa.SmallInteger(), nullable=True, comment='届/年级'),
    sa.Column('head_teacher_id', sa.Integer(), nullable=True, comment='负责教师'),
    sa.Column('group_count', sa.SmallInteger(), server_default=sa.text('1'), nullable=False, comment='列表展示冗余'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False, comment='ACTIVE/ARCHIVED'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', app.core.types.TZDateTime(), nullable=True, comment='软删除时间'),
    sa.ForeignKeyConstraint(['head_teacher_id'], ['sys_user.id'], name=op.f('fk_class_info_head_teacher_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_info'))
    )
    with op.batch_alter_table('class_info', schema=None) as batch_op:
        batch_op.create_index('idx_class_info_teacher', ['head_teacher_id'], unique=False)

    op.create_table('file_asset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True, comment='上传人'),
    sa.Column('bucket', sa.String(length=100), nullable=False, comment='对象存储桶'),
    sa.Column('object_key', sa.String(length=255), nullable=False, comment='对象键'),
    sa.Column('original_name', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('content_type', sa.String(length=100), nullable=True, comment='MIME 类型'),
    sa.Column('size_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='文件大小（字节）'),
    sa.Column('sha256', sa.String(length=64), nullable=True, comment='文件摘要'),
    sa.Column('biz_type', sa.String(length=30), nullable=False, comment='SUBMISSION/AVATAR/CERT_PDF/IMPORT/REPORT'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False, comment='ACTIVE/INVALID'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['uploader_id'], ['sys_user.id'], name=op.f('fk_file_asset_uploader_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_asset')),
    sa.UniqueConstraint('bucket', 'object_key', name='uk_file_asset_object')
    )
    op.create_table('growth_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level_type', sa.String(length=20), nullable=False, comment='BASIC/ADVANCED/EXPANDED'),
    sa.Column('unlock_condition_json', sa.JSON(), server_default=sa.text("'{}'"), nullable=False, comment='该层级的解锁条件'),
    sa.Column('skill_max_level', sa.SmallInteger(), server_default=sa.text('1'), nullable=False, comment='技能书最大等级'),
    sa.Column('pass_score', sa.Numeric(precision=5, scale=2), server_default=sa.text('(60)'), nullable=False, comment='该层级项目完成及格线'),
    sa.Column('level_description', sa.Text(), nullable=True, comment='等级说明'),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='是否启用'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='最后修改人'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['updated_by'], ['sys_user.id'], name=op.f('fk_growth_rule_updated_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growth_rule')),
    sa.UniqueConstraint('level_type', name='uk_growth_rule_level')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False, comment='岗位名称'),
    sa.Column('direction_tag', sa.String(length=50), nullable=True, comment='岗位方向标签'),
    sa.Column('recommended_level', sa.String(length=20), nullable=True, comment='BASIC/ADVANCED/EXPANDED'),
    sa.Column('scene', sa.String(length=100), nullable=True, comment='适配实训场景'),
    sa.Column('description', sa.Text(), nullable=True, comment='说明/描述'),
    sa.Column('heat', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='热度（事件更新）'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ENABLED'"), nullable=False, comment='ENABLED/DISABLED'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', app.core.types.TZDateTime(), nullable=True, comment='软删除时间'),
    sa.ForeignKeyConstraint(['created_by'], ['sys_user.id'], name=op.f('fk_job_created_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job')),
    sa.UniqueConstraint('job_name', name='uk_job_name')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index('idx_job_status', ['status', 'recommended_level'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='通知标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='通知内容'),
    sa.Column('biz_type', sa.String(length=50), nullable=True, comment='REVIEW_RESULT/STAGE_RESULT/TASK_PUBLISH/CERT/POINT'),
    sa.Column('biz_id', sa.BigInteger(), nullable=True, comment='关联业务 ID'),
    sa.Column('read_at', app.core.types.TZDateTime(), nullable=True, comment='已读时间'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['sys_user.id'], name=op.f('fk_notification_recipient_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('idx_notification_recipient', ['recipient_user_id', 'read_at'], unique=False)

    op.create_table('operation_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作人'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='业务模块'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作动作'),
    sa.Column('target_type', sa.String(length=50), nullable=True, comment='操作对象类型'),
    sa.Column('target_id', sa.BigInteger(), nullable=True, comment='操作对象 ID'),
    sa.Column('detail_json', sa.JSON(), server_default=sa.text("'{}'"), nullable=False, comment='变更前后快照'),
    sa.Column('ip', sa.String(length=45), nullable=True, comment='客户端 IP'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='客户端 User-Agent'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['operator_id'], ['sys_user.id'], name=op.f('fk_operation_log_operator_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_log'))
    )
    with op.batch_alter_table('operation_log', schema=None) as batch_op:
        batch_op.create_index('idx_operation_log_module', ['module', 'created_at'], unique=False)
        batch_op.create_index('idx_operation_log_operator', ['operator_id', 'created_at'], unique=False)

    op.create_table('skill_node',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False, comment='技能树 ID'),
    sa.Column('node_code', sa.String(length=50), nullable=False, comment='技能节点编码'),
    sa.Column('node_name', sa.String(length=100), nullable=False, comment='技能节点名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='说明/描述'),
    sa.Column('unlock_note', sa.String(length=255), nullable=True, comment='给学生看的解锁说明'),
    sa.Column('unlock_rule_json', sa.JSON(), server_default=sa.text("'{}'"), nullable=False, comment='未解锁提示规则（权威关系在 project_skill）'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ENABLED'"), nullable=False, comment='ENABLED/DISABLED'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', app.core.types.TZDateTime(), nullable=True, comment='软删除时间'),
    sa.ForeignKeyConstraint(['tree_id'], ['skill_tree.id'], name=op.f('fk_skill_node_tree_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_node')),
    sa.UniqueConstraint('node_code', name='uk_skill_node_code')
    )
    with op.batch_alter_table('skill_node', schema=None) as batch_op:
        batch_op.create_index('idx_skill_node_tree', ['tree_id'], unique=False)

    op.create_table('sys_role_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['permission_id'], ['sys_permission.id'], name=op.f('fk_sys_role_permission_permission_id')),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], name=op.f('fk_sys_role_permission_role_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_role_permission')),
    sa.UniqueConstraint('role_id', 'permission_id', name='uk_sys_role_perm')
    )
    op.create_table('sys_user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['assigned_by'], ['sys_user.id'], name=op.f('fk_sys_user_role_assigned_by')),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], name=op.f('fk_sys_user_role_role_id')),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], name=op.f('fk_sys_user_role_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_user_role')),
    sa.UniqueConstraint('user_id', 'role_id', name='uk_sys_user_role')
    )
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('config_value', sa.JSON(), server_default=sa.text("'{}'"), nullable=False, comment='配置值（JSON）'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='配置说明'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='最后修改人'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['updated_by'], ['sys_user.id'], name=op.f('fk_system_config_updated_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_config')),
    sa.UniqueConstraint('config_key', name='uk_system_config_key')
    )
    op.create_table('ai_qa_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='USER/ASSISTANT'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('model_name', sa.String(length=100), nullable=True, comment='模型名称'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True, comment='输入 Token 数'),
    sa.Column('completion_tokens', sa.Integer(), nullable=True, comment='输出 Token 数'),
    sa.Column('status', sa.String(length=20), server_default='COMPLETED', nullable=False, comment='COMPLETED/FAILED'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['session_id'], ['ai_qa_session.id'], name=op.f('fk_ai_qa_message_session_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_qa_message'))
    )
    with op.batch_alter_table('ai_qa_message', schema=None) as batch_op:
        batch_op.create_index('idx_qa_message_session', ['session_id', 'created_at'], unique=False)

    op.create_table('class_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False, comment='班级 ID'),
    sa.Column('group_no', sa.SmallInteger(), nullable=False, comment='分组序号'),
    sa.Column('group_name', sa.String(length=50), nullable=False, comment='分组名称'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['class_id'], ['class_info.id'], name=op.f('fk_class_group_class_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_group')),
    sa.UniqueConstraint('class_id', 'group_no', name='uk_class_group_no')
    )
    with op.batch_alter_table('class_group', schema=None) as batch_op:
        batch_op.create_index('idx_class_group_class', ['class_id'], unique=False)

    op.create_table('class_student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ENROLLED'"), nullable=False, comment='ENROLLED/LEFT'),
    sa.Column('enrolled_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='入班时间'),
    sa.Column('left_at', app.core.types.TZDateTime(), nullable=True, comment='离班/转出时间'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['class_id'], ['class_info.id'], name=op.f('fk_class_student_class_id')),
    sa.ForeignKeyConstraint(['student_id'], ['sys_user.id'], name=op.f('fk_class_student_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_student'))
    )
    with op.batch_alter_table('class_student', schema=None) as batch_op:
        batch_op.create_index('idx_class_student_student', ['student_id', 'status'], unique=False)
        batch_op.create_index('uk_class_student_active', ['class_id', 'student_id'], unique=True, sqlite_where=sa.text("status = 'ENROLLED'"))

    op.create_table('job_skill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('skill_node_id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_job_skill_job_id')),
    sa.ForeignKeyConstraint(['skill_node_id'], ['skill_node.id'], name=op.f('fk_job_skill_skill_node_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_skill')),
    sa.UniqueConstraint('job_id', 'skill_node_id', name='uk_job_skill')
    )
    with op.batch_alter_table('job_skill', schema=None) as batch_op:
        batch_op.create_index('idx_job_skill_skill', ['skill_node_id'], unique=False)

    op.create_table('knowledge_doc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='知识文档标题'),
    sa.Column('biz_type', sa.String(length=30), nullable=True, comment='JOB/COURSE/SYSTEM'),
    sa.Column('biz_id', sa.BigInteger(), nullable=True, comment='关联业务 ID'),
    sa.Column('file_asset_id', sa.Integer(), nullable=True, comment='文件 ID'),
    sa.Column('source', sa.String(length=30), server_default='UPLOAD', nullable=False, comment='UPLOAD/TEXT'),
    sa.Column('description', sa.Text(), nullable=True, comment='说明/描述'),
    sa.Column('status', sa.String(length=20), server_default='PARSING', nullable=False, comment='PARSING/READY/FAILED/DISABLED'),
    sa.Column('total_chunks', sa.Integer(), server_default='0', nullable=False, comment='切片总数'),
    sa.Column('uploaded_by', sa.Integer(), nullable=True, comment='上传人'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', app.core.types.TZDateTime(), nullable=True, comment='软删除时间'),
    sa.ForeignKeyConstraint(['file_asset_id'], ['file_asset.id'], name=op.f('fk_knowledge_doc_file_asset_id')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['sys_user.id'], name=op.f('fk_knowledge_doc_uploaded_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_doc'))
    )
    op.create_table('skill_node_dependency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_node_id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.CheckConstraint('node_id <> prerequisite_node_id', name=op.f('chk_skill_node_not_self')),
    sa.ForeignKeyConstraint(['node_id'], ['skill_node.id'], name=op.f('fk_skill_node_dependency_node_id')),
    sa.ForeignKeyConstraint(['prerequisite_node_id'], ['skill_node.id'], name=op.f('fk_skill_node_dependency_prerequisite_node_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_node_dependency')),
    sa.UniqueConstraint('node_id', 'prerequisite_node_id', name='uk_skill_node_dep')
    )
    op.create_table('student_certificate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False, comment='认证岗位'),
    sa.Column('certificate_no', sa.String(length=64), nullable=False, comment='证书编号'),
    sa.Column('cert_name', sa.String(length=100), nullable=False, comment='证书名称快照'),
    sa.Column('issue_org_name', sa.String(length=150), nullable=True, comment='认证机构快照'),
    sa.Column('issue_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False, comment='发放日期'),
    sa.Column('expire_date', sa.Date(), nullable=True, comment='有效期至'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'VALID'"), nullable=False, comment='VALID/EXPIRED/REVOKED/RESSUED'),
    sa.Column('issued_by', sa.Integer(), nullable=True, comment='发放人'),
    sa.Column('file_asset_id', sa.Integer(), nullable=True, comment='电子证书文件'),
    sa.Column('revoke_reason', sa.String(length=255), nullable=True, comment='作废原因'),
    sa.Column('replaced_by_id', sa.Integer(), nullable=True, comment='补发后新证书 ID'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['file_asset_id'], ['file_asset.id'], name=op.f('fk_student_certificate_file_asset_id')),
    sa.ForeignKeyConstraint(['issued_by'], ['sys_user.id'], name=op.f('fk_student_certificate_issued_by')),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_student_certificate_job_id')),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['student_certificate.id'], name=op.f('fk_student_certificate_replaced_by_id')),
    sa.ForeignKeyConstraint(['student_id'], ['sys_user.id'], name=op.f('fk_student_certificate_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_certificate')),
    sa.UniqueConstraint('certificate_no', name='uk_certificate_no')
    )
    with op.batch_alter_table('student_certificate', schema=None) as batch_op:
        batch_op.create_index('idx_student_cert_job', ['job_id', 'status'], unique=False)
        batch_op.create_index('idx_student_cert_student', ['student_id', 'status'], unique=False)

    op.create_table('student_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否当前主岗位（每人至多一个）'),
    sa.Column('selected_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='选择时间'),
    sa.Column('switched_at', app.core.types.TZDateTime(), nullable=True, comment='切换时间'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_student_job_job_id')),
    sa.ForeignKeyConstraint(['student_id'], ['sys_user.id'], name=op.f('fk_student_job_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_job')),
    sa.UniqueConstraint('student_id', 'job_id', name='uk_student_job')
    )
    with op.batch_alter_table('student_job', schema=None) as batch_op:
        batch_op.create_index('idx_student_job_student', ['student_id', 'is_primary'], unique=False)
        batch_op.create_index('uk_student_job_primary', ['student_id'], unique=True, sqlite_where=sa.text('is_primary'))

    op.create_table('student_skill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_node_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), server_default=sa.text("'LOCKED'"), nullable=False, comment='LOCKED/ACTIVATED/MASTERED'),
    sa.Column('level', sa.SmallInteger(), server_default=sa.text('0'), nullable=False, comment='熟练等级（预留）'),
    sa.Column('progress', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False, comment='0~100：完成数 ÷ 关联项目总数'),
    sa.Column('activated_at', app.core.types.TZDateTime(), nullable=True, comment='点亮时间'),
    sa.Column('mastered_at', app.core.types.TZDateTime(), nullable=True, comment='精通时间'),
    sa.Column('source', sa.String(length=30), nullable=True, comment='PROJECT/REVIEW/MANUAL'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['skill_node_id'], ['skill_node.id'], name=op.f('fk_student_skill_skill_node_id')),
    sa.ForeignKeyConstraint(['student_id'], ['sys_user.id'], name=op.f('fk_student_skill_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_skill')),
    sa.UniqueConstraint('student_id', 'skill_node_id', name='uk_student_skill')
    )
    with op.batch_alter_table('student_skill', schema=None) as batch_op:
        batch_op.create_index('idx_student_skill_node', ['skill_node_id'], unique=False)

    op.create_table('training_project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.String(length=150), nullable=False, comment='项目名称'),
    sa.Column('project_level', sa.String(length=20), nullable=False, comment='BASIC/ADVANCED/EXPANDED'),
    sa.Column('difficulty', sa.SmallInteger(), server_default=sa.text('3'), nullable=False, comment='难度 1~5'),
    sa.Column('job_id', sa.Integer(), nullable=True, comment='绑定岗位（可空）'),
    sa.Column('description', sa.Text(), nullable=True, comment='说明/描述'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'DRAFT'"), nullable=False, comment='DRAFT/PUBLISHED/OFF_SHELF'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', app.core.types.TZDateTime(), nullable=True, comment='软删除时间'),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 5', name=op.f('chk_training_project_difficulty')),
    sa.ForeignKeyConstraint(['creator_id'], ['sys_user.id'], name=op.f('fk_training_project_creator_id')),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_training_project_job_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_project')),
    sa.UniqueConstraint('project_name', name='uk_training_project_name')
    )
    with op.batch_alter_table('training_project', schema=None) as batch_op:
        batch_op.create_index('idx_training_project_status', ['project_level', 'status'], unique=False)

    op.create_table('class_student_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_student_id', sa.Integer(), nullable=False, comment='在班记录 ID'),
    sa.Column('group_id', sa.Integer(), nullable=False, comment='分组 ID'),
    sa.Column('assigned_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='分配时间'),
    sa.Column('assigned_by', sa.Integer(), nullable=True, comment='分配人'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['assigned_by'], ['sys_user.id'], name=op.f('fk_class_student_group_assigned_by')),
    sa.ForeignKeyConstraint(['class_student_id'], ['class_student.id'], name=op.f('fk_class_student_group_class_student_id')),
    sa.ForeignKeyConstraint(['group_id'], ['class_group.id'], name=op.f('fk_class_student_group_group_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_student_group')),
    sa.UniqueConstraint('class_student_id', name=op.f('uk_class_student_group_class_student_id'))
    )
    with op.batch_alter_table('class_student_group', schema=None) as batch_op:
        batch_op.create_index('idx_class_student_group_group', ['group_id'], unique=False)

    op.create_table('knowledge_chunk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='切片序号'),
    sa.Column('content', sa.Text(), nullable=False, comment='切片正文'),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='内容哈希'),
    sa.Column('char_count', sa.Integer(), server_default='0', nullable=False, comment='字符数'),
    sa.Column('vector_id', sa.String(length=64), nullable=True, comment='Milvus 主键'),
    sa.Column('model_name', sa.String(length=100), nullable=True, comment='模型名称'),
    sa.Column('status', sa.String(length=20), server_default='READY', nullable=False, comment='READY/FAILED/DISABLED'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['doc_id'], ['knowledge_doc.id'], name=op.f('fk_knowledge_chunk_doc_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunk')),
    sa.UniqueConstraint('doc_id', 'chunk_index', name='uk_knowledge_chunk')
    )
    with op.batch_alter_table('knowledge_chunk', schema=None) as batch_op:
        batch_op.create_index('idx_knowledge_chunk_doc', ['doc_id', 'chunk_index'], unique=False)

    op.create_table('project_module',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True, comment='来自模块库；自定义模块为空'),
    sa.Column('stage_key', sa.String(length=50), nullable=True, comment='标准模块 code；自定义为空'),
    sa.Column('module_name', sa.String(length=100), nullable=False, comment='模块名称'),
    sa.Column('stage_no', sa.SmallInteger(), nullable=False, comment='项目内填写顺序'),
    sa.Column('requirement', sa.Text(), nullable=True, comment='作答要求（覆盖模板）'),
    sa.Column('accept_standard', sa.Text(), nullable=True, comment='验收标准（覆盖模板）'),
    sa.Column('required', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='是否必填'),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False, comment='分值占比'),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='是否启用'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['training_project.id'], name=op.f('fk_project_module_project_id')),
    sa.ForeignKeyConstraint(['template_id'], ['project_stage_template.id'], name=op.f('fk_project_module_template_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_module')),
    sa.UniqueConstraint('project_id', 'stage_key', name='uk_project_module_key'),
    sa.UniqueConstraint('project_id', 'stage_no', name='uk_project_module_no')
    )
    with op.batch_alter_table('project_module', schema=None) as batch_op:
        batch_op.create_index('idx_project_module_project', ['project_id', 'stage_no'], unique=False)

    op.create_table('project_skill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('skill_node_id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['project_id'], ['training_project.id'], name=op.f('fk_project_skill_project_id')),
    sa.ForeignKeyConstraint(['skill_node_id'], ['skill_node.id'], name=op.f('fk_project_skill_skill_node_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_skill')),
    sa.UniqueConstraint('project_id', 'skill_node_id', name='uk_project_skill')
    )
    with op.batch_alter_table('project_skill', schema=None) as batch_op:
        batch_op.create_index('idx_project_skill_node', ['skill_node_id'], unique=False)

    op.create_table('student_project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'NOT_STARTED'"), nullable=False, comment='NOT_STARTED/IN_PROGRESS/SUBMITTED/COMPLETED'),
    sa.Column('progress', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False, comment='0~100：已填写模块 ÷ 启用模块'),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='当前（最新）成绩'),
    sa.Column('best_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='历史最高成绩'),
    sa.Column('attempt_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False, comment='闯关轮次数量'),
    sa.Column('started_at', app.core.types.TZDateTime(), nullable=True, comment='开始时间'),
    sa.Column('completed_at', app.core.types.TZDateTime(), nullable=True, comment='完成时间'),
    sa.Column('completed_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='完成时的分数快照'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['training_project.id'], name=op.f('fk_student_project_project_id')),
    sa.ForeignKeyConstraint(['student_id'], ['sys_user.id'], name=op.f('fk_student_project_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_project')),
    sa.UniqueConstraint('student_id', 'project_id', name='uk_student_project')
    )
    with op.batch_alter_table('student_project', schema=None) as batch_op:
        batch_op.create_index('idx_student_project_project', ['project_id'], unique=False)
        batch_op.create_index('idx_student_project_student', ['student_id', 'status'], unique=False)

    op.create_table('ai_qa_citation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=True, comment='知识文档 ID'),
    sa.Column('chunk_id', sa.Integer(), nullable=True, comment='知识切片 ID'),
    sa.Column('source_title', sa.String(length=255), nullable=True, comment='引用来源标题快照'),
    sa.Column('snippet', sa.Text(), nullable=True, comment='引用片段快照'),
    sa.Column('relevance', sa.Numeric(precision=6, scale=4), nullable=True, comment='相关度 0~1'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunk.id'], name=op.f('fk_ai_qa_citation_chunk_id')),
    sa.ForeignKeyConstraint(['doc_id'], ['knowledge_doc.id'], name=op.f('fk_ai_qa_citation_doc_id')),
    sa.ForeignKeyConstraint(['message_id'], ['ai_qa_message.id'], name=op.f('fk_ai_qa_citation_message_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_qa_citation'))
    )
    with op.batch_alter_table('ai_qa_citation', schema=None) as batch_op:
        batch_op.create_index('idx_qa_citation_message', ['message_id'], unique=False)

    op.create_table('training_attempt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_project_id', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.SmallInteger(), nullable=False, comment='轮次序号'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'IN_PROGRESS'"), nullable=False, comment='IN_PROGRESS/SUBMITTED/COMPLETED/ABANDONED'),
    sa.Column('filled_stage_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False, comment='已填写模块数'),
    sa.Column('submitted_at', app.core.types.TZDateTime(), nullable=True, comment='整单提交时间'),
    sa.Column('finished_at', app.core.types.TZDateTime(), nullable=True, comment='评审结束时间'),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='本轮得分'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['student_project_id'], ['student_project.id'], name=op.f('fk_training_attempt_student_project_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_attempt')),
    sa.UniqueConstraint('student_project_id', 'attempt_no', name='uk_training_attempt')
    )
    with op.batch_alter_table('training_attempt', schema=None) as batch_op:
        batch_op.create_index('idx_training_attempt_project', ['student_project_id', 'status'], unique=False)

    op.create_table('attempt_stage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('project_module_id', sa.Integer(), nullable=False),
    sa.Column('is_filled', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='该模块是否已填写完成'),
    sa.Column('answer_text', sa.Text(), nullable=True, comment='作答文本内容'),
    sa.Column('filled_at', app.core.types.TZDateTime(), nullable=True, comment='填写完成时间'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['attempt_id'], ['training_attempt.id'], name=op.f('fk_attempt_stage_attempt_id')),
    sa.ForeignKeyConstraint(['project_module_id'], ['project_module.id'], name=op.f('fk_attempt_stage_project_module_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempt_stage')),
    sa.UniqueConstraint('attempt_id', 'project_module_id', name='uk_attempt_stage')
    )
    with op.batch_alter_table('attempt_stage', schema=None) as batch_op:
        batch_op.create_index('idx_attempt_stage_module', ['project_module_id'], unique=False)

    op.create_table('project_submission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('submit_no', sa.SmallInteger(), nullable=False, comment='整单提交序号'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'PENDING_AI'"), nullable=False, comment='PENDING_AI/AI_PASSED/AI_FAILED/PENDING_REVIEW/REVIEWING/REVIEWED/WITHDRAWN'),
    sa.Column('final_conclusion', sa.String(length=10), nullable=True, comment='PASS/FAIL'),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='本次提交总分'),
    sa.Column('objection_reason', sa.String(length=500), nullable=True, comment='学生对 AI 结果的异议说明'),
    sa.Column('is_starred', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='教师标星'),
    sa.Column('submitted_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='整单提交时间'),
    sa.Column('withdrawn_at', app.core.types.TZDateTime(), nullable=True, comment='学生撤回时间'),
    sa.Column('reviewed_at', app.core.types.TZDateTime(), nullable=True, comment='评审完成时间'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['attempt_id'], ['training_attempt.id'], name=op.f('fk_project_submission_attempt_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_submission')),
    sa.UniqueConstraint('attempt_id', 'submit_no', name='uk_project_submission')
    )
    op.create_table('attempt_stage_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempt_stage_id', sa.Integer(), nullable=False),
    sa.Column('file_asset_id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['attempt_stage_id'], ['attempt_stage.id'], name=op.f('fk_attempt_stage_file_attempt_stage_id')),
    sa.ForeignKeyConstraint(['file_asset_id'], ['file_asset.id'], name=op.f('fk_attempt_stage_file_file_asset_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempt_stage_file')),
    sa.UniqueConstraint('attempt_stage_id', 'file_asset_id', name='uk_attempt_stage_file')
    )
    op.create_table('review_ai_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('job_status', sa.String(length=20), server_default=sa.text("'QUEUED'"), nullable=False, comment='QUEUED/PROCESSING/SUCCEED/FAILED'),
    sa.Column('model_name', sa.String(length=100), nullable=True, comment='执行批阅的 AI 模型'),
    sa.Column('request_id', sa.String(length=100), nullable=True, comment='AI 服务请求 ID'),
    sa.Column('error_msg', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('attempt_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False, comment='已尝试次数'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('finished_at', app.core.types.TZDateTime(), nullable=True, comment='结束时间'),
    sa.ForeignKeyConstraint(['submission_id'], ['project_submission.id'], name=op.f('fk_review_ai_job_submission_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_ai_job'))
    )
    with op.batch_alter_table('review_ai_job', schema=None) as batch_op:
        batch_op.create_index('idx_review_ai_job_status', ['job_status', 'created_at'], unique=False)

    op.create_table('review_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('review_kind', sa.String(length=20), nullable=False, comment='AI/TEACHER'),
    sa.Column('version_no', sa.SmallInteger(), server_default=sa.text('1'), nullable=False, comment='版本号'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'DRAFT'"), nullable=False, comment='DRAFT/FINAL'),
    sa.Column('reviewer_id', sa.Integer(), nullable=True, comment='教师；AI 为空'),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='本次评审总分'),
    sa.Column('conclusion', sa.String(length=10), nullable=True, comment='PASS/FAIL'),
    sa.Column('comment', sa.Text(), nullable=True, comment='评语/批注'),
    sa.Column('dimension_json', sa.JSON(), server_default=sa.text("'[]'"), nullable=False, comment='各维度得分与理由'),
    sa.Column('ai_model', sa.String(length=100), nullable=True, comment='AI 模型名称'),
    sa.Column('raw_json', sa.JSON(), server_default=sa.text("'{}'"), nullable=False, comment='AI 原始返回快照'),
    sa.Column('created_at', app.core.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('finished_at', app.core.types.TZDateTime(), nullable=True, comment='结束时间'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['sys_user.id'], name=op.f('fk_review_record_reviewer_id')),
    sa.ForeignKeyConstraint(['submission_id'], ['project_submission.id'], name=op.f('fk_review_record_submission_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_record')),
    sa.UniqueConstraint('submission_id', 'review_kind', 'version_no', name='uk_review_record')
    )
    # 表达式索引（DESC 排序 / 部分索引）：SQLite 的索引反射不支持，
    # autogenerate 会跳过，这里按模型定义手工补齐。
    op.execute(
        'CREATE INDEX idx_project_submission_status ON project_submission (status, submitted_at DESC)'
    )
    op.execute(
        'CREATE INDEX idx_project_submission_starred ON project_submission '
        '(is_starred, submitted_at DESC) WHERE is_starred'
    )
    op.execute(
        'CREATE INDEX idx_review_record_submission ON review_record '
        '(submission_id, review_kind, version_no DESC)'
    )
    op.execute(
        'CREATE INDEX idx_qa_session_student ON ai_qa_session (student_id, updated_at DESC)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute('DROP INDEX IF EXISTS idx_qa_session_student')
    op.execute('DROP INDEX IF EXISTS idx_review_record_submission')
    op.execute('DROP INDEX IF EXISTS idx_project_submission_starred')
    op.execute('DROP INDEX IF EXISTS idx_project_submission_status')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_record')
    with op.batch_alter_table('review_ai_job', schema=None) as batch_op:
        batch_op.drop_index('idx_review_ai_job_status')

    op.drop_table('review_ai_job')
    op.drop_table('attempt_stage_file')
    op.drop_table('project_submission')
    with op.batch_alter_table('attempt_stage', schema=None) as batch_op:
        batch_op.drop_index('idx_attempt_stage_module')

    op.drop_table('attempt_stage')
    with op.batch_alter_table('training_attempt', schema=None) as batch_op:
        batch_op.drop_index('idx_training_attempt_project')

    op.drop_table('training_attempt')
    with op.batch_alter_table('ai_qa_citation', schema=None) as batch_op:
        batch_op.drop_index('idx_qa_citation_message')

    op.drop_table('ai_qa_citation')
    with op.batch_alter_table('student_project', schema=None) as batch_op:
        batch_op.drop_index('idx_student_project_student')
        batch_op.drop_index('idx_student_project_project')

    op.drop_table('student_project')
    with op.batch_alter_table('project_skill', schema=None) as batch_op:
        batch_op.drop_index('idx_project_skill_node')

    op.drop_table('project_skill')
    with op.batch_alter_table('project_module', schema=None) as batch_op:
        batch_op.drop_index('idx_project_module_project')

    op.drop_table('project_module')
    with op.batch_alter_table('knowledge_chunk', schema=None) as batch_op:
        batch_op.drop_index('idx_knowledge_chunk_doc')

    op.drop_table('knowledge_chunk')
    with op.batch_alter_table('class_student_group', schema=None) as batch_op:
        batch_op.drop_index('idx_class_student_group_group')

    op.drop_table('class_student_group')
    with op.batch_alter_table('training_project', schema=None) as batch_op:
        batch_op.drop_index('idx_training_project_status')

    op.drop_table('training_project')
    with op.batch_alter_table('student_skill', schema=None) as batch_op:
        batch_op.drop_index('idx_student_skill_node')

    op.drop_table('student_skill')
    with op.batch_alter_table('student_job', schema=None) as batch_op:
        batch_op.drop_index('uk_student_job_primary', sqlite_where=sa.text('is_primary'))
        batch_op.drop_index('idx_student_job_student')

    op.drop_table('student_job')
    with op.batch_alter_table('student_certificate', schema=None) as batch_op:
        batch_op.drop_index('idx_student_cert_student')
        batch_op.drop_index('idx_student_cert_job')

    op.drop_table('student_certificate')
    op.drop_table('skill_node_dependency')
    op.drop_table('knowledge_doc')
    with op.batch_alter_table('job_skill', schema=None) as batch_op:
        batch_op.drop_index('idx_job_skill_skill')

    op.drop_table('job_skill')
    with op.batch_alter_table('class_student', schema=None) as batch_op:
        batch_op.drop_index('uk_class_student_active', sqlite_where=sa.text("status = 'ENROLLED'"))
        batch_op.drop_index('idx_class_student_student')

    op.drop_table('class_student')
    with op.batch_alter_table('class_group', schema=None) as batch_op:
        batch_op.drop_index('idx_class_group_class')

    op.drop_table('class_group')
    with op.batch_alter_table('ai_qa_message', schema=None) as batch_op:
        batch_op.drop_index('idx_qa_message_session')

    op.drop_table('ai_qa_message')
    op.drop_table('system_config')
    op.drop_table('sys_user_role')
    op.drop_table('sys_role_permission')
    with op.batch_alter_table('skill_node', schema=None) as batch_op:
        batch_op.drop_index('idx_skill_node_tree')

    op.drop_table('skill_node')
    with op.batch_alter_table('operation_log', schema=None) as batch_op:
        batch_op.drop_index('idx_operation_log_operator')
        batch_op.drop_index('idx_operation_log_module')

    op.drop_table('operation_log')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('idx_notification_recipient')

    op.drop_table('notification')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index('idx_job_status')

    op.drop_table('job')
    op.drop_table('growth_rule')
    op.drop_table('file_asset')
    with op.batch_alter_table('class_info', schema=None) as batch_op:
        batch_op.drop_index('idx_class_info_teacher')

    op.drop_table('class_info')
    op.drop_table('ai_qa_session')
    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.drop_index('uk_sys_user_ext', sqlite_where=sa.text('ext_uid IS NOT NULL'))
        batch_op.drop_index('idx_sys_user_type_status')

    op.drop_table('sys_user')
    op.drop_table('sys_role')
    op.drop_table('sys_permission')
    op.drop_table('skill_tree')
    op.drop_table('project_stage_template')
    # ### end Alembic commands ###
