"""删掉模块库的默认子标题（default_items_json）

Revision ID: 82a4f9ff26f4
Revises: a7e2d4cc4467
Create Date: 2026-09-13 21:11:01.131555

子标题不该由模板预设：不同岗位方向的实训项目子标题差别很大（检测类讲缺陷定义、
成像类讲光源镜头），模板给默认值反而会误导教师。改为全部由教师在项目关卡里手填，
模板只保留编码/名称/默认权重/默认要求这些通用信息。
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '82a4f9ff26f4'
down_revision: str | None = 'a7e2d4cc4467'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_stage_template', schema=None) as batch_op:
        batch_op.drop_column('default_items_json')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_stage_template', schema=None) as batch_op:
        # 回滚时表里可能已有数据，非空列必须带临时默认值才加得上
        batch_op.add_column(
            sa.Column(
                'default_items_json', sqlite.JSON(), nullable=False, server_default=sa.text("'[]'")
            )
        )

    # ### end Alembic commands ###
