"""新增 J 域任务下发：publish_task / target / job / project

Revision ID: 8b2df4d8233d
Revises: 996df7ebcc4a
Create Date: 2026-09-15 22:01:29.867016

背景：`training_project.status = 'PUBLISHED'` 只表示"项目已编辑完成、可被任务引用"；
学生可见 = 项目被一条已生效（status = 'PUBLISHED'）的任务覆盖到该学生。
岗位范围（publish_task_job）只用于筛项目（training_project.job_id），不筛学生，无记录 = 全部岗位。

两条部分唯一索引（全班目标 / 分组目标）SQLite 无法反射，autogenerate 会跳过，这里手工补齐。
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8b2df4d8233d'
down_revision: str | None = '996df7ebcc4a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publish_task',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('publish_mode', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint(
        "(publish_mode = 'SCHEDULED' AND scheduled_at IS NOT NULL) OR publish_mode <> 'SCHEDULED'",
        name='chk_publish_task_schedule',
    ),
    sa.ForeignKeyConstraint(['creator_id'], ['sys_user.id'], name=op.f('fk_publish_task_creator_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publish_task'))
    )
    with op.batch_alter_table('publish_task', schema=None) as batch_op:
        batch_op.create_index('idx_publish_task_status', ['status', 'scheduled_at'], unique=False)
        batch_op.create_index('idx_publish_task_creator', ['creator_id', 'created_at'], unique=False)

    op.create_table('publish_task_target',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint(
        "(target_type = 'CLASS' AND group_id IS NULL) OR (target_type = 'GROUP' AND group_id IS NOT NULL)",
        name='chk_publish_task_target_group',
    ),
    sa.ForeignKeyConstraint(['task_id'], ['publish_task.id'], name=op.f('fk_publish_task_target_task_id')),
    sa.ForeignKeyConstraint(['class_id'], ['class_info.id'], name=op.f('fk_publish_task_target_class_id')),
    sa.ForeignKeyConstraint(['group_id'], ['class_group.id'], name=op.f('fk_publish_task_target_group_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publish_task_target'))
    )
    with op.batch_alter_table('publish_task_target', schema=None) as batch_op:
        batch_op.create_index('idx_publish_task_target_class', ['class_id', 'target_type'], unique=False)
        # 一个任务对一个班最多一条"全班"目标；一个任务对一个分组最多一条 —— NULL 互不相等，必须用部分索引
        batch_op.create_index(
            'uk_publish_task_target_class',
            ['task_id', 'class_id'],
            unique=True,
            sqlite_where=sa.text('group_id IS NULL'),
        )
        batch_op.create_index(
            'uk_publish_task_target_group',
            ['task_id', 'group_id'],
            unique=True,
            sqlite_where=sa.text('group_id IS NOT NULL'),
        )

    op.create_table('publish_task_job',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['publish_task.id'], name=op.f('fk_publish_task_job_task_id')),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_publish_task_job_job_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publish_task_job')),
    sa.UniqueConstraint('task_id', 'job_id', name='uk_publish_task_job')
    )

    op.create_table('publish_task_project',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sort_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['publish_task.id'], name=op.f('fk_publish_task_project_task_id')),
    sa.ForeignKeyConstraint(
        ['project_id'], ['training_project.id'], name=op.f('fk_publish_task_project_project_id')
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publish_task_project')),
    sa.UniqueConstraint('task_id', 'project_id', name='uk_publish_task_project')
    )
    with op.batch_alter_table('publish_task_project', schema=None) as batch_op:
        batch_op.create_index('idx_publish_task_project_project', ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publish_task_project', schema=None) as batch_op:
        batch_op.drop_index('idx_publish_task_project_project')
    op.drop_table('publish_task_project')

    op.drop_table('publish_task_job')

    with op.batch_alter_table('publish_task_target', schema=None) as batch_op:
        batch_op.drop_index('uk_publish_task_target_group', sqlite_where=sa.text('group_id IS NOT NULL'))
        batch_op.drop_index('uk_publish_task_target_class', sqlite_where=sa.text('group_id IS NULL'))
        batch_op.drop_index('idx_publish_task_target_class')
    op.drop_table('publish_task_target')

    with op.batch_alter_table('publish_task', schema=None) as batch_op:
        batch_op.drop_index('idx_publish_task_creator')
        batch_op.drop_index('idx_publish_task_status')
    op.drop_table('publish_task')
    # ### end Alembic commands ###
