"""模块库与项目关卡加填写引导子标题（items_json）

Revision ID: a7e2d4cc4467
Revises: 15607e58a390
Create Date: 2026-09-13 21:05:44.438272

子标题只做填写引导（不参与校验与评分），因此用 JSON 存：
project_stage_template.default_items_json = 模板默认子标题；
project_module.items_json = 本项目实际使用的子标题（加关卡时从模板复制，之后项目可改）。
存量行统一补空数组，避免加非空列时被已有数据挡住。
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a7e2d4cc4467'
down_revision: str | None = '15607e58a390'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_module', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('items_json', sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
        )

    with op.batch_alter_table('project_stage_template', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('default_items_json', sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
        )

    # 存量行回填后把库级默认值摘掉：项目约定"默认值只写在 Python 侧"，
    # 留着 server_default 会让 alembic check 一直报差异。
    with op.batch_alter_table('project_module', schema=None) as batch_op:
        batch_op.alter_column(
            'items_json', existing_type=sa.JSON(), nullable=False, server_default=None
        )

    with op.batch_alter_table('project_stage_template', schema=None) as batch_op:
        batch_op.alter_column(
            'default_items_json', existing_type=sa.JSON(), nullable=False, server_default=None
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_stage_template', schema=None) as batch_op:
        batch_op.drop_column('default_items_json')

    with op.batch_alter_table('project_module', schema=None) as batch_op:
        batch_op.drop_column('items_json')

    # ### end Alembic commands ###
