"""project_module 只存选中的模块库模板：template_id 必填，去掉 enabled / stage_key / module_name

Revision ID: c29c7ea1e713
Revises: 3f4a00612ab8
Create Date: 2026-09-13 20:25:35.363787

背景：模块库（project_stage_template）是关卡的唯一来源，项目只能挑模板；
没被选中的模板不落库，所以 enabled 没有意义，自定义模块的字段也一并去掉。
表级唯一约束从 (project_id, stage_key) 改为 (project_id, template_id)。
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'c29c7ea1e713'
down_revision: str | None = '3f4a00612ab8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_module', schema=None) as batch_op:
        batch_op.alter_column('template_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('uk_project_module_key'), type_='unique')
        batch_op.create_unique_constraint('uk_project_module_template', ['project_id', 'template_id'])
        batch_op.drop_column('module_name')
        batch_op.drop_column('stage_key')
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_module', schema=None) as batch_op:
        # 回滚时表里可能已有数据，非空列必须带临时默认值才加得上
        batch_op.add_column(sa.Column('enabled', sa.BOOLEAN(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('stage_key', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(
            sa.Column('module_name', sa.VARCHAR(length=100), nullable=False, server_default='')
        )
        batch_op.drop_constraint('uk_project_module_template', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uk_project_module_key'), ['project_id', 'stage_key'])
        batch_op.alter_column('template_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
