"""init schema

Revision ID: d5b772b56392
Revises: 
Create Date: 2026-09-11 01:41:37.115055
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd5b772b56392'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_stage_template',
    sa.Column('stage_key', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('stage_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_required', sa.Boolean(), nullable=False),
    sa.Column('default_weight', sa.Numeric(), nullable=False),
    sa.Column('default_requirement', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_accept_standard', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sort_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_stage_template')),
    sa.UniqueConstraint('stage_key', name='uk_stage_template_key')
    )
    op.create_table('skill_tree',
    sa.Column('tree_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('tree_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_tree')),
    sa.UniqueConstraint('tree_code', name='uk_skill_tree_code')
    )
    op.create_table('sys_permission',
    sa.Column('perm_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('perm_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_permission')),
    sa.UniqueConstraint('perm_code', name='uk_sys_perm_code')
    )
    op.create_table('sys_role',
    sa.Column('role_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('role_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_role')),
    sa.UniqueConstraint('role_code', name='uk_sys_role_code')
    )
    op.create_table('sys_user',
    sa.Column('user_no', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('real_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('user_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('ext_uid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('major_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_user')),
    sa.UniqueConstraint('user_no', name='uk_sys_user_no')
    )
    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.create_index('idx_sys_user_type_status', ['user_type', 'status'], unique=False)
        batch_op.create_index('uk_sys_user_ext', ['ext_uid'], unique=True, sqlite_where=sa.text('ext_uid IS NOT NULL'))

    op.create_table('ai_qa_session',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['sys_user.id'], name=op.f('fk_ai_qa_session_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_qa_session'))
    )
    op.create_table('class_info',
    sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('grade_year', sa.Integer(), nullable=True),
    sa.Column('head_teacher_id', sa.Integer(), nullable=True),
    sa.Column('group_count', sa.Integer(), nullable=False),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['head_teacher_id'], ['sys_user.id'], name=op.f('fk_class_info_head_teacher_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_info'))
    )
    with op.batch_alter_table('class_info', schema=None) as batch_op:
        batch_op.create_index('idx_class_info_teacher', ['head_teacher_id'], unique=False)

    op.create_table('file_asset',
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('bucket', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('object_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('original_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('biz_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['sys_user.id'], name=op.f('fk_file_asset_uploader_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_asset')),
    sa.UniqueConstraint('bucket', 'object_key', name='uk_file_asset_object')
    )
    op.create_table('growth_rule',
    sa.Column('level_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('unlock_condition_json', sa.JSON(), nullable=False),
    sa.Column('skill_max_level', sa.Integer(), nullable=False),
    sa.Column('pass_score', sa.Numeric(), nullable=False),
    sa.Column('level_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['sys_user.id'], name=op.f('fk_growth_rule_updated_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growth_rule')),
    sa.UniqueConstraint('level_type', name='uk_growth_rule_level')
    )
    op.create_table('job',
    sa.Column('job_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('direction_tag', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('recommended_level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('scene', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('heat', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['sys_user.id'], name=op.f('fk_job_created_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job')),
    sa.UniqueConstraint('job_name', name='uk_job_name')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index('idx_job_status', ['status', 'recommended_level'], unique=False)

    op.create_table('notification',
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('biz_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('biz_id', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['sys_user.id'], name=op.f('fk_notification_recipient_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('idx_notification_recipient', ['recipient_user_id', 'read_at'], unique=False)

    op.create_table('operation_log',
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detail_json', sa.JSON(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['sys_user.id'], name=op.f('fk_operation_log_operator_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_log'))
    )
    with op.batch_alter_table('operation_log', schema=None) as batch_op:
        batch_op.create_index('idx_operation_log_module', ['module', 'created_at'], unique=False)
        batch_op.create_index('idx_operation_log_operator', ['operator_id', 'created_at'], unique=False)

    op.create_table('skill_node',
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('node_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('node_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unlock_note', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('unlock_rule_json', sa.JSON(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['skill_tree.id'], name=op.f('fk_skill_node_tree_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_node')),
    sa.UniqueConstraint('node_code', name='uk_skill_node_code')
    )
    with op.batch_alter_table('skill_node', schema=None) as batch_op:
        batch_op.create_index('idx_skill_node_tree', ['tree_id'], unique=False)

    op.create_table('sys_role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['sys_permission.id'], name=op.f('fk_sys_role_permission_permission_id')),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], name=op.f('fk_sys_role_permission_role_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_role_permission')),
    sa.UniqueConstraint('role_id', 'permission_id', name='uk_sys_role_perm')
    )
    op.create_table('sys_user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['sys_user.id'], name=op.f('fk_sys_user_role_assigned_by')),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], name=op.f('fk_sys_user_role_role_id')),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], name=op.f('fk_sys_user_role_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_user_role')),
    sa.UniqueConstraint('user_id', 'role_id', name='uk_sys_user_role')
    )
    op.create_table('system_config',
    sa.Column('config_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('config_value', sa.JSON(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['sys_user.id'], name=op.f('fk_system_config_updated_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_config')),
    sa.UniqueConstraint('config_key', name='uk_system_config_key')
    )
    op.create_table('ai_qa_message',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_qa_session.id'], name=op.f('fk_ai_qa_message_session_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_qa_message'))
    )
    with op.batch_alter_table('ai_qa_message', schema=None) as batch_op:
        batch_op.create_index('idx_qa_message_session', ['session_id', 'created_at'], unique=False)

    op.create_table('class_group',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('group_no', sa.Integer(), nullable=False),
    sa.Column('group_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class_info.id'], name=op.f('fk_class_group_class_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_group')),
    sa.UniqueConstraint('class_id', 'group_no', name='uk_class_group_no')
    )
    with op.batch_alter_table('class_group', schema=None) as batch_op:
        batch_op.create_index('idx_class_group_class', ['class_id'], unique=False)

    op.create_table('class_student',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class_info.id'], name=op.f('fk_class_student_class_id')),
    sa.ForeignKeyConstraint(['student_id'], ['sys_user.id'], name=op.f('fk_class_student_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_student'))
    )
    with op.batch_alter_table('class_student', schema=None) as batch_op:
        batch_op.create_index('idx_class_student_student', ['student_id', 'status'], unique=False)
        batch_op.create_index('uk_class_student_active', ['class_id', 'student_id'], unique=True, sqlite_where=sa.text("status = 'ENROLLED'"))

    op.create_table('job_skill',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('skill_node_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_job_skill_job_id')),
    sa.ForeignKeyConstraint(['skill_node_id'], ['skill_node.id'], name=op.f('fk_job_skill_skill_node_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_skill')),
    sa.UniqueConstraint('job_id', 'skill_node_id', name='uk_job_skill')
    )
    with op.batch_alter_table('job_skill', schema=None) as batch_op:
        batch_op.create_index('idx_job_skill_skill', ['skill_node_id'], unique=False)

    op.create_table('knowledge_doc',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('biz_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('biz_id', sa.Integer(), nullable=True),
    sa.Column('file_asset_id', sa.Integer(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_asset_id'], ['file_asset.id'], name=op.f('fk_knowledge_doc_file_asset_id')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['sys_user.id'], name=op.f('fk_knowledge_doc_uploaded_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_doc'))
    )
    op.create_table('skill_node_dependency',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_node_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('node_id <> prerequisite_node_id', name=op.f('chk_skill_node_not_self')),
    sa.ForeignKeyConstraint(['node_id'], ['skill_node.id'], name=op.f('fk_skill_node_dependency_node_id')),
    sa.ForeignKeyConstraint(['prerequisite_node_id'], ['skill_node.id'], name=op.f('fk_skill_node_dependency_prerequisite_node_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_node_dependency')),
    sa.UniqueConstraint('node_id', 'prerequisite_node_id', name='uk_skill_node_dep')
    )
    op.create_table('student_certificate',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('certificate_no', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('cert_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('issue_org_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expire_date', sa.Date(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('issued_by', sa.Integer(), nullable=True),
    sa.Column('file_asset_id', sa.Integer(), nullable=True),
    sa.Column('revoke_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('replaced_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_asset_id'], ['file_asset.id'], name=op.f('fk_student_certificate_file_asset_id')),
    sa.ForeignKeyConstraint(['issued_by'], ['sys_user.id'], name=op.f('fk_student_certificate_issued_by')),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_student_certificate_job_id')),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['student_certificate.id'], name=op.f('fk_student_certificate_replaced_by_id')),
    sa.ForeignKeyConstraint(['student_id'], ['sys_user.id'], name=op.f('fk_student_certificate_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_certificate')),
    sa.UniqueConstraint('certificate_no', name='uk_certificate_no')
    )
    with op.batch_alter_table('student_certificate', schema=None) as batch_op:
        batch_op.create_index('idx_student_cert_job', ['job_id', 'status'], unique=False)
        batch_op.create_index('idx_student_cert_student', ['student_id', 'status'], unique=False)

    op.create_table('student_job',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('selected_at', sa.DateTime(), nullable=False),
    sa.Column('switched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_student_job_job_id')),
    sa.ForeignKeyConstraint(['student_id'], ['sys_user.id'], name=op.f('fk_student_job_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_job')),
    sa.UniqueConstraint('student_id', 'job_id', name='uk_student_job')
    )
    with op.batch_alter_table('student_job', schema=None) as batch_op:
        batch_op.create_index('idx_student_job_student', ['student_id', 'is_primary'], unique=False)
        batch_op.create_index('uk_student_job_primary', ['student_id'], unique=True, sqlite_where=sa.text('is_primary'))

    op.create_table('student_skill',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_node_id', sa.Integer(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Numeric(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('mastered_at', sa.DateTime(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_node_id'], ['skill_node.id'], name=op.f('fk_student_skill_skill_node_id')),
    sa.ForeignKeyConstraint(['student_id'], ['sys_user.id'], name=op.f('fk_student_skill_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_skill')),
    sa.UniqueConstraint('student_id', 'skill_node_id', name='uk_student_skill')
    )
    with op.batch_alter_table('student_skill', schema=None) as batch_op:
        batch_op.create_index('idx_student_skill_node', ['skill_node_id'], unique=False)

    op.create_table('training_project',
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('project_level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 5', name=op.f('chk_training_project_difficulty')),
    sa.ForeignKeyConstraint(['creator_id'], ['sys_user.id'], name=op.f('fk_training_project_creator_id')),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_training_project_job_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_project')),
    sa.UniqueConstraint('project_name', name='uk_training_project_name')
    )
    with op.batch_alter_table('training_project', schema=None) as batch_op:
        batch_op.create_index('idx_training_project_status', ['project_level', 'status'], unique=False)

    op.create_table('class_student_group',
    sa.Column('class_student_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['sys_user.id'], name=op.f('fk_class_student_group_assigned_by')),
    sa.ForeignKeyConstraint(['class_student_id'], ['class_student.id'], name=op.f('fk_class_student_group_class_student_id')),
    sa.ForeignKeyConstraint(['group_id'], ['class_group.id'], name=op.f('fk_class_student_group_group_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_student_group')),
    sa.UniqueConstraint('class_student_id', name=op.f('uk_class_student_group_class_student_id'))
    )
    with op.batch_alter_table('class_student_group', schema=None) as batch_op:
        batch_op.create_index('idx_class_student_group_group', ['group_id'], unique=False)

    op.create_table('knowledge_chunk',
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('vector_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['knowledge_doc.id'], name=op.f('fk_knowledge_chunk_doc_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunk')),
    sa.UniqueConstraint('doc_id', 'chunk_index', name='uk_knowledge_chunk')
    )
    with op.batch_alter_table('knowledge_chunk', schema=None) as batch_op:
        batch_op.create_index('idx_knowledge_chunk_doc', ['doc_id', 'chunk_index'], unique=False)

    op.create_table('project_module',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('stage_key', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('module_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('stage_no', sa.Integer(), nullable=False),
    sa.Column('requirement', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accept_standard', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Numeric(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['training_project.id'], name=op.f('fk_project_module_project_id')),
    sa.ForeignKeyConstraint(['template_id'], ['project_stage_template.id'], name=op.f('fk_project_module_template_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_module')),
    sa.UniqueConstraint('project_id', 'stage_key', name='uk_project_module_key'),
    sa.UniqueConstraint('project_id', 'stage_no', name='uk_project_module_no')
    )
    with op.batch_alter_table('project_module', schema=None) as batch_op:
        batch_op.create_index('idx_project_module_project', ['project_id', 'stage_no'], unique=False)

    op.create_table('project_skill',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('skill_node_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['training_project.id'], name=op.f('fk_project_skill_project_id')),
    sa.ForeignKeyConstraint(['skill_node_id'], ['skill_node.id'], name=op.f('fk_project_skill_skill_node_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_skill')),
    sa.UniqueConstraint('project_id', 'skill_node_id', name='uk_project_skill')
    )
    with op.batch_alter_table('project_skill', schema=None) as batch_op:
        batch_op.create_index('idx_project_skill_node', ['skill_node_id'], unique=False)

    op.create_table('student_project',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('progress', sa.Numeric(), nullable=False),
    sa.Column('total_score', sa.Numeric(), nullable=True),
    sa.Column('best_score', sa.Numeric(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['training_project.id'], name=op.f('fk_student_project_project_id')),
    sa.ForeignKeyConstraint(['student_id'], ['sys_user.id'], name=op.f('fk_student_project_student_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_project')),
    sa.UniqueConstraint('student_id', 'project_id', name='uk_student_project')
    )
    with op.batch_alter_table('student_project', schema=None) as batch_op:
        batch_op.create_index('idx_student_project_project', ['project_id'], unique=False)
        batch_op.create_index('idx_student_project_student', ['student_id', 'status'], unique=False)

    op.create_table('ai_qa_citation',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('source_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('snippet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('relevance', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunk.id'], name=op.f('fk_ai_qa_citation_chunk_id')),
    sa.ForeignKeyConstraint(['doc_id'], ['knowledge_doc.id'], name=op.f('fk_ai_qa_citation_doc_id')),
    sa.ForeignKeyConstraint(['message_id'], ['ai_qa_message.id'], name=op.f('fk_ai_qa_citation_message_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_qa_citation'))
    )
    with op.batch_alter_table('ai_qa_citation', schema=None) as batch_op:
        batch_op.create_index('idx_qa_citation_message', ['message_id'], unique=False)

    op.create_table('training_attempt',
    sa.Column('student_project_id', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('filled_stage_count', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('total_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_project_id'], ['student_project.id'], name=op.f('fk_training_attempt_student_project_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_attempt')),
    sa.UniqueConstraint('student_project_id', 'attempt_no', name='uk_training_attempt')
    )
    with op.batch_alter_table('training_attempt', schema=None) as batch_op:
        batch_op.create_index('idx_training_attempt_project', ['student_project_id', 'status'], unique=False)

    op.create_table('attempt_stage',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('project_module_id', sa.Integer(), nullable=False),
    sa.Column('is_filled', sa.Boolean(), nullable=False),
    sa.Column('answer_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['training_attempt.id'], name=op.f('fk_attempt_stage_attempt_id')),
    sa.ForeignKeyConstraint(['project_module_id'], ['project_module.id'], name=op.f('fk_attempt_stage_project_module_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempt_stage')),
    sa.UniqueConstraint('attempt_id', 'project_module_id', name='uk_attempt_stage')
    )
    with op.batch_alter_table('attempt_stage', schema=None) as batch_op:
        batch_op.create_index('idx_attempt_stage_module', ['project_module_id'], unique=False)

    op.create_table('project_submission',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('submit_no', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('final_conclusion', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('total_score', sa.Numeric(), nullable=True),
    sa.Column('objection_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['training_attempt.id'], name=op.f('fk_project_submission_attempt_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_submission')),
    sa.UniqueConstraint('attempt_id', 'submit_no', name='uk_project_submission')
    )
    op.create_table('attempt_stage_file',
    sa.Column('attempt_stage_id', sa.Integer(), nullable=False),
    sa.Column('file_asset_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_stage_id'], ['attempt_stage.id'], name=op.f('fk_attempt_stage_file_attempt_stage_id')),
    sa.ForeignKeyConstraint(['file_asset_id'], ['file_asset.id'], name=op.f('fk_attempt_stage_file_file_asset_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempt_stage_file')),
    sa.UniqueConstraint('attempt_stage_id', 'file_asset_id', name='uk_attempt_stage_file')
    )
    op.create_table('review_ai_job',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('job_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('error_msg', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['project_submission.id'], name=op.f('fk_review_ai_job_submission_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_ai_job'))
    )
    with op.batch_alter_table('review_ai_job', schema=None) as batch_op:
        batch_op.create_index('idx_review_ai_job_status', ['job_status', 'created_at'], unique=False)

    op.create_table('review_record',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('review_kind', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Numeric(), nullable=True),
    sa.Column('conclusion', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dimension_json', sa.JSON(), nullable=False),
    sa.Column('ai_model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['sys_user.id'], name=op.f('fk_review_record_reviewer_id')),
    sa.ForeignKeyConstraint(['submission_id'], ['project_submission.id'], name=op.f('fk_review_record_submission_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_record')),
    sa.UniqueConstraint('submission_id', 'review_kind', 'version_no', name='uk_review_record')
    )
    # 表达式索引（DESC 排序 / 部分索引）：SQLite 无法反射，autogenerate 会跳过，
    # 这里按模型定义手工补齐。新增同类索引时请同步修改本文件与 env.py 的 EXPRESSION_INDEXES。
    op.execute(
        'CREATE INDEX idx_project_submission_status ON project_submission (status, submitted_at DESC)'
    )
    op.execute(
        'CREATE INDEX idx_project_submission_starred ON project_submission '
        '(is_starred, submitted_at DESC) WHERE is_starred'
    )
    op.execute(
        'CREATE INDEX idx_review_record_submission ON review_record '
        '(submission_id, review_kind, version_no DESC)'
    )
    op.execute(
        'CREATE INDEX idx_qa_session_student ON ai_qa_session (student_id, updated_at DESC)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute('DROP INDEX IF EXISTS idx_qa_session_student')
    op.execute('DROP INDEX IF EXISTS idx_review_record_submission')
    op.execute('DROP INDEX IF EXISTS idx_project_submission_starred')
    op.execute('DROP INDEX IF EXISTS idx_project_submission_status')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_record')
    with op.batch_alter_table('review_ai_job', schema=None) as batch_op:
        batch_op.drop_index('idx_review_ai_job_status')

    op.drop_table('review_ai_job')
    op.drop_table('attempt_stage_file')
    op.drop_table('project_submission')
    with op.batch_alter_table('attempt_stage', schema=None) as batch_op:
        batch_op.drop_index('idx_attempt_stage_module')

    op.drop_table('attempt_stage')
    with op.batch_alter_table('training_attempt', schema=None) as batch_op:
        batch_op.drop_index('idx_training_attempt_project')

    op.drop_table('training_attempt')
    with op.batch_alter_table('ai_qa_citation', schema=None) as batch_op:
        batch_op.drop_index('idx_qa_citation_message')

    op.drop_table('ai_qa_citation')
    with op.batch_alter_table('student_project', schema=None) as batch_op:
        batch_op.drop_index('idx_student_project_student')
        batch_op.drop_index('idx_student_project_project')

    op.drop_table('student_project')
    with op.batch_alter_table('project_skill', schema=None) as batch_op:
        batch_op.drop_index('idx_project_skill_node')

    op.drop_table('project_skill')
    with op.batch_alter_table('project_module', schema=None) as batch_op:
        batch_op.drop_index('idx_project_module_project')

    op.drop_table('project_module')
    with op.batch_alter_table('knowledge_chunk', schema=None) as batch_op:
        batch_op.drop_index('idx_knowledge_chunk_doc')

    op.drop_table('knowledge_chunk')
    with op.batch_alter_table('class_student_group', schema=None) as batch_op:
        batch_op.drop_index('idx_class_student_group_group')

    op.drop_table('class_student_group')
    with op.batch_alter_table('training_project', schema=None) as batch_op:
        batch_op.drop_index('idx_training_project_status')

    op.drop_table('training_project')
    with op.batch_alter_table('student_skill', schema=None) as batch_op:
        batch_op.drop_index('idx_student_skill_node')

    op.drop_table('student_skill')
    with op.batch_alter_table('student_job', schema=None) as batch_op:
        batch_op.drop_index('uk_student_job_primary', sqlite_where=sa.text('is_primary'))
        batch_op.drop_index('idx_student_job_student')

    op.drop_table('student_job')
    with op.batch_alter_table('student_certificate', schema=None) as batch_op:
        batch_op.drop_index('idx_student_cert_student')
        batch_op.drop_index('idx_student_cert_job')

    op.drop_table('student_certificate')
    op.drop_table('skill_node_dependency')
    op.drop_table('knowledge_doc')
    with op.batch_alter_table('job_skill', schema=None) as batch_op:
        batch_op.drop_index('idx_job_skill_skill')

    op.drop_table('job_skill')
    with op.batch_alter_table('class_student', schema=None) as batch_op:
        batch_op.drop_index('uk_class_student_active', sqlite_where=sa.text("status = 'ENROLLED'"))
        batch_op.drop_index('idx_class_student_student')

    op.drop_table('class_student')
    with op.batch_alter_table('class_group', schema=None) as batch_op:
        batch_op.drop_index('idx_class_group_class')

    op.drop_table('class_group')
    with op.batch_alter_table('ai_qa_message', schema=None) as batch_op:
        batch_op.drop_index('idx_qa_message_session')

    op.drop_table('ai_qa_message')
    op.drop_table('system_config')
    op.drop_table('sys_user_role')
    op.drop_table('sys_role_permission')
    with op.batch_alter_table('skill_node', schema=None) as batch_op:
        batch_op.drop_index('idx_skill_node_tree')

    op.drop_table('skill_node')
    with op.batch_alter_table('operation_log', schema=None) as batch_op:
        batch_op.drop_index('idx_operation_log_operator')
        batch_op.drop_index('idx_operation_log_module')

    op.drop_table('operation_log')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('idx_notification_recipient')

    op.drop_table('notification')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index('idx_job_status')

    op.drop_table('job')
    op.drop_table('growth_rule')
    op.drop_table('file_asset')
    with op.batch_alter_table('class_info', schema=None) as batch_op:
        batch_op.drop_index('idx_class_info_teacher')

    op.drop_table('class_info')
    op.drop_table('ai_qa_session')
    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.drop_index('uk_sys_user_ext', sqlite_where=sa.text('ext_uid IS NOT NULL'))
        batch_op.drop_index('idx_sys_user_type_status')

    op.drop_table('sys_user')
    op.drop_table('sys_role')
    op.drop_table('sys_permission')
    op.drop_table('skill_tree')
    op.drop_table('project_stage_template')
    # ### end Alembic commands ###
