-- =====================================================================
-- 岗位闯关式实训平台 · 数据库表架构 DDL（v0.3-P0 单学院版）
-- 依据：docs/岗位闯关式实训平台-需求确认书0706.docx（P0 范围）
-- 目标：PostgreSQL 15+
-- 说明：
--   1) 服务对象为单个学院；枚举以 varchar code 保存；
--   2) 项目由“模块库”挑选模块组成（project_module）；
--   3) 闯关为“全部关卡填写完成后整单提交”，不做单关提交；
--   4) 及格线统一在 growth_rule（按基础/进阶/拓展），不在项目上重复配置；
--   5) 技能进度 = 已完成关联项目数 ÷ 关联项目总数；
--   6) 任务下发（publish_*）、积分称号、评审维度字典本期不做。
-- =====================================================================

-- =====================================================================
-- A 域：账户与权限（6 张）
-- =====================================================================

CREATE TABLE sys_user (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_no       varchar(50)  NOT NULL,                 -- 学号/工号
    real_name     varchar(50)  NOT NULL,
    user_type     varchar(20)  NOT NULL,                 -- STUDENT/TEACHER/ADMIN
    ext_uid       varchar(64),                           -- 学校 IDP 唯一标识
    major_name    varchar(100),                          -- 专业（学生信息/名单导入）
    avatar_url    varchar(255),
    phone         varchar(32),
    email         varchar(128),
    status        varchar(20)  NOT NULL DEFAULT 'ACTIVE',-- ACTIVE/DISABLED
    last_login_at timestamptz,
    remark        varchar(255),
    created_at    timestamptz  NOT NULL DEFAULT now(),
    updated_at    timestamptz  NOT NULL DEFAULT now(),
    deleted_at    timestamptz,
    CONSTRAINT uk_sys_user_no UNIQUE (user_no)
);
CREATE UNIQUE INDEX uk_sys_user_ext ON sys_user (ext_uid) WHERE ext_uid IS NOT NULL;
COMMENT ON TABLE sys_user IS '平台用户：单学院内学生/教师/管理员；不存密码，身份来自校方 SSO';

CREATE TABLE sys_role (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code  varchar(50) NOT NULL,
    role_name  varchar(50) NOT NULL,
    password   varchar(100),                             -- 预留：mock 登录/联调用，正式走 SSO
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_sys_role_code UNIQUE (role_code)
);
COMMENT ON TABLE sys_role IS '角色定义（教师/学生/管理员）；password 仅为后续 mock 预留';

CREATE TABLE sys_permission (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perm_code  varchar(100) NOT NULL,
    perm_name  varchar(100) NOT NULL,
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uk_sys_perm_code UNIQUE (perm_code)
);
COMMENT ON TABLE sys_permission IS '权限点（扁平结构，无父子层级、无排序）';

CREATE TABLE sys_user_role (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint NOT NULL REFERENCES sys_user (id),
    role_id     bigint NOT NULL REFERENCES sys_role (id),
    assigned_by bigint REFERENCES sys_user (id),
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_sys_user_role UNIQUE (user_id, role_id)
);

CREATE TABLE sys_role_permission (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id       bigint NOT NULL REFERENCES sys_role (id),
    permission_id bigint NOT NULL REFERENCES sys_permission (id),
    created_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_sys_role_perm UNIQUE (role_id, permission_id)
);

CREATE TABLE system_config (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key   varchar(100) NOT NULL,
    config_value jsonb        NOT NULL DEFAULT '{}',
    description  varchar(255),
    updated_by   bigint REFERENCES sys_user (id),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_system_config_key UNIQUE (config_key)
);

-- =====================================================================
-- B 域：教学组织（4 张）
-- =====================================================================

CREATE TABLE class_info (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_name      varchar(100) NOT NULL,
    grade_year      smallint,                            -- 届/年级
    head_teacher_id bigint REFERENCES sys_user (id),     -- 负责教师
    group_count     smallint     NOT NULL DEFAULT 1,     -- 列表展示冗余
    remark          varchar(255),
    status          varchar(20)  NOT NULL DEFAULT 'ACTIVE', -- ACTIVE/ARCHIVED
    created_at      timestamptz  NOT NULL DEFAULT now(),
    updated_at      timestamptz  NOT NULL DEFAULT now(),
    deleted_at      timestamptz
);

CREATE TABLE class_group (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id   bigint NOT NULL REFERENCES class_info (id),
    group_no   smallint     NOT NULL,
    group_name varchar(50)  NOT NULL,
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uk_class_group_no UNIQUE (class_id, group_no)
);

CREATE TABLE class_student (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id    bigint NOT NULL REFERENCES class_info (id),
    student_id  bigint NOT NULL REFERENCES sys_user (id),
    status      varchar(20) NOT NULL DEFAULT 'ENROLLED', -- ENROLLED/LEFT
    enrolled_at timestamptz NOT NULL DEFAULT now(),
    left_at     timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_class_student_active
    ON class_student (class_id, student_id) WHERE status = 'ENROLLED';

CREATE TABLE class_student_group (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_student_id bigint NOT NULL UNIQUE REFERENCES class_student (id),
    group_id         bigint NOT NULL REFERENCES class_group (id),
    assigned_at      timestamptz NOT NULL DEFAULT now(),
    assigned_by      bigint REFERENCES sys_user (id),
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now()
);

-- =====================================================================
-- C 域：岗位与技能成长（9 张；project_skill 因依赖项目表后置）
-- =====================================================================

CREATE TABLE job (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name          varchar(100) NOT NULL,
    direction_tag     varchar(50),                       -- 方向标签，如工业视觉
    recommended_level varchar(20),                       -- BASIC/ADVANCED/EXPANDED
    scene             varchar(100),                      -- 适配实训场景
    description       text,
    heat              bigint       NOT NULL DEFAULT 0,   -- 热度（事件更新）
    status            varchar(20)  NOT NULL DEFAULT 'ENABLED', -- ENABLED/DISABLED
    created_by        bigint REFERENCES sys_user (id),
    created_at        timestamptz  NOT NULL DEFAULT now(),
    updated_at        timestamptz  NOT NULL DEFAULT now(),
    deleted_at        timestamptz,
    CONSTRAINT uk_job_name UNIQUE (job_name)
);

CREATE TABLE student_job (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id  bigint NOT NULL REFERENCES sys_user (id),
    job_id      bigint NOT NULL REFERENCES job (id),
    is_primary  boolean     NOT NULL DEFAULT false,
    selected_at timestamptz NOT NULL DEFAULT now(),
    switched_at timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_student_job UNIQUE (student_id, job_id)
);
CREATE UNIQUE INDEX uk_student_job_primary
    ON student_job (student_id) WHERE is_primary;

CREATE TABLE skill_tree (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tree_code   varchar(50)  NOT NULL,
    tree_name   varchar(100) NOT NULL,
    description varchar(255),
    status      varchar(20)  NOT NULL DEFAULT 'ENABLED',
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now(),
    deleted_at  timestamptz,
    CONSTRAINT uk_skill_tree_code UNIQUE (tree_code)
);

CREATE TABLE skill_node (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tree_id          bigint NOT NULL REFERENCES skill_tree (id),
    node_code        varchar(50)  NOT NULL,
    node_name        varchar(100) NOT NULL,
    description      text,
    unlock_note      varchar(255),                       -- 给学生看的解锁说明
    unlock_rule_json jsonb NOT NULL DEFAULT '{}',        -- 未解锁提示用；权威关系在 project_skill
    status           varchar(20) NOT NULL DEFAULT 'ENABLED',
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    deleted_at       timestamptz,
    CONSTRAINT uk_skill_node_code UNIQUE (node_code)
);

CREATE TABLE skill_node_dependency (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id              bigint NOT NULL REFERENCES skill_node (id),
    prerequisite_node_id bigint NOT NULL REFERENCES skill_node (id),
    created_at           timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_skill_node_dep UNIQUE (node_id, prerequisite_node_id),
    CONSTRAINT chk_skill_node_not_self CHECK (node_id <> prerequisite_node_id)
);

CREATE TABLE student_skill (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id    bigint NOT NULL REFERENCES sys_user (id),
    skill_node_id bigint NOT NULL REFERENCES skill_node (id),
    state         varchar(20) NOT NULL DEFAULT 'LOCKED', -- LOCKED/ACTIVATED/MASTERED
    level         smallint NOT NULL DEFAULT 0,           -- 熟练等级（预留）
    progress      numeric(5,2) NOT NULL DEFAULT 0,       -- 0~100：完成数 ÷ 关联项目总数
    activated_at  timestamptz,
    mastered_at   timestamptz,
    source        varchar(30),                           -- PROJECT/REVIEW/MANUAL
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_student_skill UNIQUE (student_id, skill_node_id)
);

CREATE TABLE job_skill (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id        bigint NOT NULL REFERENCES job (id),
    skill_node_id bigint NOT NULL REFERENCES skill_node (id),
    created_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_job_skill UNIQUE (job_id, skill_node_id)
);
COMMENT ON TABLE job_skill IS '岗位-技能关联；不设要求程度/权重，岗位推荐按学生技能进度计算';

CREATE TABLE growth_rule (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level_type            varchar(20) NOT NULL,          -- BASIC/ADVANCED/EXPANDED
    unlock_condition_json jsonb NOT NULL DEFAULT '{}',   -- 该层级的解锁条件
    skill_max_level       smallint NOT NULL DEFAULT 1,   -- 技能书最大等级
    pass_score            numeric(5,2) NOT NULL DEFAULT 60, -- 该层级的项目完成及格线
    level_description     text,
    enabled               boolean NOT NULL DEFAULT true,
    updated_by            bigint REFERENCES sys_user (id),
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_growth_rule_level UNIQUE (level_type)
);
COMMENT ON TABLE growth_rule IS '按实训层级统一配置解锁条件、技能书最大等级、项目及格线与等级说明';

-- =====================================================================
-- D 域：实训项目（3 张）
-- =====================================================================

CREATE TABLE training_project (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name  varchar(150) NOT NULL,
    project_level varchar(20)  NOT NULL,                 -- BASIC/ADVANCED/EXPANDED
    difficulty    smallint     NOT NULL DEFAULT 3,       -- 难度 1~5
    job_id        bigint REFERENCES job (id),            -- 绑定岗位（可空）
    description   text,
    status        varchar(20)  NOT NULL DEFAULT 'DRAFT', -- DRAFT/PUBLISHED/OFF_SHELF
    creator_id    bigint REFERENCES sys_user (id),
    created_at    timestamptz  NOT NULL DEFAULT now(),
    updated_at    timestamptz  NOT NULL DEFAULT now(),
    deleted_at    timestamptz,
    CONSTRAINT uk_training_project_name UNIQUE (project_name),
    CONSTRAINT chk_training_project_difficulty CHECK (difficulty BETWEEN 1 AND 5)
);
COMMENT ON TABLE training_project IS '实训项目主数据；完成及格线不在此配置，统一读 growth_rule.pass_score';

-- C 域项目-技能关系表：因引用 training_project，放置于项目表创建之后
CREATE TABLE project_skill (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id    bigint NOT NULL REFERENCES training_project (id),
    skill_node_id bigint NOT NULL REFERENCES skill_node (id),
    created_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_project_skill UNIQUE (project_id, skill_node_id)
);
COMMENT ON TABLE project_skill IS '项目-技能多对多关系：完成关联项目即推进该技能进度（完成数/关联项目总数）';

CREATE TABLE project_stage_template (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage_key               varchar(50)  NOT NULL,       -- 七大模块 code
    stage_name              varchar(100) NOT NULL,
    description             text,
    default_required        boolean      NOT NULL DEFAULT true,
    default_weight          numeric(5,2) NOT NULL DEFAULT 0,
    default_requirement     text,                        -- 默认作答要求
    default_accept_standard text,                        -- 默认验收标准
    sort_no                 int NOT NULL DEFAULT 0,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_stage_template_key UNIQUE (stage_key)
);
COMMENT ON TABLE project_stage_template IS '标准化模块库（七大模块默认配置），教师建项目时从中挑选';

-- 项目模块组成：一条 = 项目中的一个模块（可来自模块库，也可自定义；数量不限）
CREATE TABLE project_module (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      bigint NOT NULL REFERENCES training_project (id),
    template_id     bigint REFERENCES project_stage_template (id), -- 来自模块库；自定义模块为空
    stage_key       varchar(50),                         -- 标准模块 code；自定义模块为空
    module_name     varchar(100) NOT NULL,               -- 模块名称（来自模板或自定义）
    stage_no        smallint     NOT NULL,               -- 项目内填写顺序，数量不限
    requirement     text,                                -- 该模块的作答要求（覆盖模板）
    accept_standard text,                                -- 该模块的验收标准（覆盖模板）
    required        boolean      NOT NULL DEFAULT true,  -- 是否必填
    weight          numeric(5,2) NOT NULL DEFAULT 0,     -- 分值占比（启用模块合计 100）
    enabled         boolean      NOT NULL DEFAULT true,  -- 是否启用
    created_at      timestamptz  NOT NULL DEFAULT now(),
    updated_at      timestamptz  NOT NULL DEFAULT now(),
    -- PostgreSQL 中 NULL 互不相等，因此多个自定义模块（stage_key 为空）可共存
    CONSTRAINT uk_project_module_key UNIQUE (project_id, stage_key),
    CONSTRAINT uk_project_module_no UNIQUE (project_id, stage_no)
);
COMMENT ON TABLE project_module IS '项目模块组成：可从模块库挑选或自定义，数量不限；一条记录代表项目中的一个模块';

-- =====================================================================
-- E 域：闯关过程与评审（8 张）
-- =====================================================================

CREATE TABLE file_asset (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uploader_id   bigint REFERENCES sys_user (id),
    bucket        varchar(100) NOT NULL,
    object_key    varchar(255) NOT NULL,
    original_name varchar(255) NOT NULL,
    content_type  varchar(100),
    size_bytes    bigint NOT NULL DEFAULT 0,
    sha256        varchar(64),
    biz_type      varchar(30) NOT NULL,                  -- SUBMISSION/AVATAR/CERT_PDF/IMPORT/REPORT
    status        varchar(20) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE/INVALID
    created_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_file_asset_object UNIQUE (bucket, object_key)
);

CREATE TABLE student_project (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      bigint NOT NULL REFERENCES sys_user (id),
    project_id      bigint NOT NULL REFERENCES training_project (id),
    status          varchar(20) NOT NULL DEFAULT 'NOT_STARTED', -- NOT_STARTED/IN_PROGRESS/SUBMITTED/COMPLETED
    progress        numeric(5,2) NOT NULL DEFAULT 0,     -- 0~100：已填写模块 ÷ 启用模块
    total_score     numeric(5,2),                        -- 当前（最新）成绩
    best_score      numeric(5,2),                        -- 历史最高成绩
    attempt_count   smallint NOT NULL DEFAULT 0,         -- 闯关轮次数量
    started_at      timestamptz,
    completed_at    timestamptz,
    completed_score numeric(5,2),                        -- 完成时的分数快照
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_student_project UNIQUE (student_id, project_id)
);
COMMENT ON TABLE student_project IS '学生实训记录：学生点击“开始闯关”时生成一条，承载填写进度、成绩与完成状态';

CREATE TABLE training_attempt (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_project_id bigint NOT NULL REFERENCES student_project (id),
    attempt_no         smallint NOT NULL,
    status             varchar(20) NOT NULL DEFAULT 'IN_PROGRESS', -- IN_PROGRESS/SUBMITTED/COMPLETED/ABANDONED
    filled_stage_count smallint NOT NULL DEFAULT 0,      -- 已填写模块数
    submitted_at       timestamptz,                      -- 整单提交时间
    finished_at        timestamptz,                      -- 评审结束时间
    total_score        numeric(5,2),                     -- 本轮得分
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_training_attempt UNIQUE (student_project_id, attempt_no)
);
COMMENT ON TABLE training_attempt IS '闯关轮次：重新挑战生成新的 attempt_no，历史保留';

CREATE TABLE attempt_stage (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id        bigint NOT NULL REFERENCES training_attempt (id),
    project_module_id bigint NOT NULL REFERENCES project_module (id),
    is_filled         boolean NOT NULL DEFAULT false,    -- 该模块是否已填写完成
    answer_text       text,                              -- 作答文本内容
    filled_at         timestamptz,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_attempt_stage UNIQUE (attempt_id, project_module_id)
);
COMMENT ON TABLE attempt_stage IS '轮次内每个模块的作答与填写状态；全部必填模块填写完成后才允许整单提交';

CREATE TABLE attempt_stage_file (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_stage_id bigint NOT NULL REFERENCES attempt_stage (id),
    file_asset_id    bigint NOT NULL REFERENCES file_asset (id),
    created_at       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_attempt_stage_file UNIQUE (attempt_stage_id, file_asset_id)
);

CREATE TABLE project_submission (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id       bigint NOT NULL REFERENCES training_attempt (id),
    submit_no        smallint NOT NULL,
    status           varchar(20) NOT NULL DEFAULT 'PENDING_AI', -- PENDING_AI/AI_PASSED/AI_FAILED/PENDING_REVIEW/REVIEWING/REVIEWED/WITHDRAWN
    final_conclusion varchar(10),                        -- PASS/FAIL
    total_score      numeric(5,2),                       -- 本次提交得分
    objection_reason varchar(500),                       -- 学生对 AI 结果的异议说明
    is_starred       boolean NOT NULL DEFAULT false,     -- 教师标星
    submitted_at     timestamptz NOT NULL DEFAULT now(),
    withdrawn_at     timestamptz,                        -- 学生撤回时间（撤回后回到填写中）
    reviewed_at      timestamptz,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_project_submission UNIQUE (attempt_id, submit_no)
);
COMMENT ON TABLE project_submission IS '整单提交记录：一次提交包含该轮次全部模块的作答，可多次重提，学生可撤回';

CREATE TABLE review_record (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id  bigint NOT NULL REFERENCES project_submission (id),
    review_kind    varchar(20)  NOT NULL,                -- AI/TEACHER
    version_no     smallint     NOT NULL DEFAULT 1,
    status         varchar(20)  NOT NULL DEFAULT 'DRAFT',-- DRAFT/FINAL
    reviewer_id    bigint REFERENCES sys_user (id),      -- 教师；AI 为空
    total_score    numeric(5,2),
    conclusion     varchar(10),                          -- PASS/FAIL
    comment        text,                                 -- 评语/批注
    dimension_json jsonb NOT NULL DEFAULT '[]',          -- 各维度得分与理由（维度由 AI/教师直接给名称）
    ai_model       varchar(100),
    raw_json       jsonb NOT NULL DEFAULT '{}',          -- AI 原始返回快照
    created_at     timestamptz NOT NULL DEFAULT now(),
    finished_at    timestamptz,
    CONSTRAINT uk_review_record UNIQUE (submission_id, review_kind, version_no)
);
COMMENT ON TABLE review_record IS '整单评审记录（AI/教师）；维度明细以 JSON 存储，不再单独建维度字典表';

CREATE TABLE review_ai_job (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id bigint NOT NULL REFERENCES project_submission (id),
    job_status    varchar(20) NOT NULL DEFAULT 'QUEUED', -- QUEUED/PROCESSING/SUCCEED/FAILED
    model_name    varchar(100),
    request_id    varchar(100),
    error_msg     text,
    attempt_count smallint NOT NULL DEFAULT 0,
    created_at    timestamptz NOT NULL DEFAULT now(),
    finished_at   timestamptz
);

-- =====================================================================
-- F 域：证书台账（1 张）
-- =====================================================================

CREATE TABLE student_certificate (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id     bigint NOT NULL REFERENCES sys_user (id),
    job_id         bigint NOT NULL REFERENCES job (id),  -- 认证岗位
    certificate_no varchar(64) NOT NULL,
    cert_name      varchar(100) NOT NULL,                -- 证书名称快照
    issue_org_name varchar(150),                         -- 认证机构快照
    issue_date     date NOT NULL DEFAULT CURRENT_DATE,
    expire_date    date,
    status         varchar(20) NOT NULL DEFAULT 'VALID', -- VALID/EXPIRED/REVOKED/RESSUED
    issued_by      bigint REFERENCES sys_user (id),
    file_asset_id  bigint REFERENCES file_asset (id),    -- 电子证书文件
    revoke_reason  varchar(255),
    replaced_by_id bigint REFERENCES student_certificate (id), -- 补发后新证指向旧证
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_certificate_no UNIQUE (certificate_no)
);

-- =====================================================================
-- H 域：AI 问答知识库（5 张）
-- =====================================================================

CREATE TABLE knowledge_doc (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         varchar(255) NOT NULL,
    biz_type      varchar(30),                           -- JOB/COURSE/SYSTEM
    biz_id        bigint,
    file_asset_id bigint REFERENCES file_asset (id),
    source        varchar(30) NOT NULL DEFAULT 'UPLOAD', -- UPLOAD/TEXT
    description   text,
    status        varchar(20) NOT NULL DEFAULT 'PARSING',-- PARSING/READY/FAILED/DISABLED
    total_chunks  int NOT NULL DEFAULT 0,
    uploaded_by   bigint REFERENCES sys_user (id),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    deleted_at    timestamptz
);

CREATE TABLE knowledge_chunk (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id       bigint NOT NULL REFERENCES knowledge_doc (id),
    chunk_index  int NOT NULL,
    content      text NOT NULL,
    content_hash varchar(64),
    char_count   int NOT NULL DEFAULT 0,
    vector_id    varchar(64),                            -- Milvus 主键
    model_name   varchar(100),
    status       varchar(20) NOT NULL DEFAULT 'READY',
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_knowledge_chunk UNIQUE (doc_id, chunk_index)
);

CREATE TABLE ai_qa_session (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL REFERENCES sys_user (id),
    title      varchar(255),
    subject    varchar(100),                             -- 课程/知识范围
    status     varchar(20) NOT NULL DEFAULT 'ACTIVE',    -- ACTIVE/CLOSED
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE ai_qa_message (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id        bigint NOT NULL REFERENCES ai_qa_session (id),
    role              varchar(20) NOT NULL,              -- USER/ASSISTANT
    content           text NOT NULL,
    model_name        varchar(100),
    prompt_tokens     int,
    completion_tokens int,
    status            varchar(20) NOT NULL DEFAULT 'COMPLETED',
    created_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE ai_qa_citation (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id   bigint NOT NULL REFERENCES ai_qa_message (id),
    doc_id       bigint REFERENCES knowledge_doc (id),
    chunk_id     bigint REFERENCES knowledge_chunk (id),
    source_title varchar(255),                           -- 引用来源标题快照
    snippet      text,                                   -- 引用片段快照
    relevance    numeric(6,4),
    created_at   timestamptz NOT NULL DEFAULT now()
);

-- =====================================================================
-- I 域：通知与审计（2 张）
-- =====================================================================

CREATE TABLE notification (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id bigint NOT NULL REFERENCES sys_user (id),
    title             varchar(255) NOT NULL,
    content           text,
    biz_type          varchar(50),                       -- REVIEW_RESULT/STAGE_RESULT/CERT
    biz_id            bigint,
    read_at           timestamptz,
    created_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE operation_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id bigint REFERENCES sys_user (id),
    module      varchar(50) NOT NULL,
    action      varchar(50) NOT NULL,
    target_type varchar(50),
    target_id   bigint,
    detail_json jsonb NOT NULL DEFAULT '{}',
    ip          varchar(45),
    user_agent  varchar(255),
    created_at  timestamptz NOT NULL DEFAULT now()
);

-- =====================================================================
-- 索引（核心热路径）
-- =====================================================================

CREATE INDEX idx_sys_user_type_status ON sys_user (user_type, status);

CREATE INDEX idx_class_info_teacher ON class_info (head_teacher_id);
CREATE INDEX idx_class_group_class ON class_group (class_id);
CREATE INDEX idx_class_student_student ON class_student (student_id, status);
CREATE INDEX idx_class_student_group_group ON class_student_group (group_id);

CREATE INDEX idx_job_status ON job (status, recommended_level);
CREATE INDEX idx_student_job_student ON student_job (student_id, is_primary);
CREATE INDEX idx_skill_node_tree ON skill_node (tree_id);
CREATE INDEX idx_student_skill_node ON student_skill (skill_node_id);
CREATE INDEX idx_project_skill_node ON project_skill (skill_node_id);
CREATE INDEX idx_job_skill_skill ON job_skill (skill_node_id);

CREATE INDEX idx_training_project_status ON training_project (project_level, status);
CREATE INDEX idx_project_module_project ON project_module (project_id, stage_no);

CREATE INDEX idx_student_project_student ON student_project (student_id, status);
CREATE INDEX idx_student_project_project ON student_project (project_id);

CREATE INDEX idx_training_attempt_project ON training_attempt (student_project_id, status);
CREATE INDEX idx_attempt_stage_module ON attempt_stage (project_module_id);

CREATE INDEX idx_project_submission_status ON project_submission (status, submitted_at DESC);
CREATE INDEX idx_project_submission_starred ON project_submission (is_starred, submitted_at DESC)
    WHERE is_starred;

CREATE INDEX idx_review_record_submission ON review_record (submission_id, review_kind, version_no DESC);
CREATE INDEX idx_review_ai_job_status ON review_ai_job (job_status, created_at);

CREATE INDEX idx_student_cert_student ON student_certificate (student_id, status);
CREATE INDEX idx_student_cert_job ON student_certificate (job_id, status);

CREATE INDEX idx_knowledge_chunk_doc ON knowledge_chunk (doc_id, chunk_index);
CREATE INDEX idx_qa_message_session ON ai_qa_message (session_id, created_at);
CREATE INDEX idx_qa_citation_message ON ai_qa_citation (message_id);
CREATE INDEX idx_qa_session_student ON ai_qa_session (student_id, updated_at DESC);

CREATE INDEX idx_notification_recipient ON notification (recipient_user_id, read_at);
CREATE INDEX idx_operation_log_module ON operation_log (module, created_at);
CREATE INDEX idx_operation_log_operator ON operation_log (operator_id, created_at);

-- 结束
